export const UserRoutes = {
  "GET_ALL_USERS": "GET_ALL_USERS",
  "GET_ONE_USER": "GET_ONE_USER",
  "GET_MANY_USERS_BY_ID": "GET_MANY_USERS_BY_ID",
  "POST_USER": "POST_USER",
  "EDIT_USER": "EDIT_USER",
  "REMOVE_USER_BY_ID": "REMOVE_USER_BY_ID",
  "REMOVE_MANY_USERS_BY_ID": "REMOVE_MANY_USERS_BY_ID",
  "REMOVE_ALL_USERS": "REMOVE_ALL_USERS"
}

export const AccountRoutes = {
  "GET_ALL_ACCOUNTS": "GET_ALL_ACCOUNTS",
  "GET_ONE_ACCOUNT": "GET_ONE_ACCOUNT",
  "GET_MANY_ACCOUNTS_BY_ID": "GET_MANY_ACCOUNTS_BY_ID",
  "POST_ACCOUNT": "POST_ACCOUNT",
  "EDIT_ACCOUNT": "EDIT_ACCOUNT",
  "REMOVE_ACCOUNT_BY_ID": "REMOVE_ACCOUNT_BY_ID",
  "REMOVE_MANY_ACCOUNTS_BY_ID": "REMOVE_MANY_ACCOUNTS_BY_ID",
  "REMOVE_ALL_ACCOUNTS": "REMOVE_ALL_ACCOUNTS"
}

export const BusinessProfileRoutes = {
  "GET_ALL_BUSINESS_PROFILES": "GET_ALL_BUSINESS_PROFILES",
  "GET_ONE_BUSINESS_PROFILE": "GET_ONE_BUSINESS_PROFILE",
  "GET_MANY_BUSINESS_PROFILES_BY_ID": "GET_MANY_BUSINESS_PROFILES_BY_ID",
  "POST_BUSINESS_PROFILE": "POST_BUSINESS_PROFILE",
  "EDIT_BUSINESS_PROFILE": "EDIT_BUSINESS_PROFILE",
  "REMOVE_BUSINESS_PROFILE_BY_ID": "REMOVE_BUSINESS_PROFILE_BY_ID",
  "REMOVE_MANY_BUSINESS_PROFILES_BY_ID": "REMOVE_MANY_BUSINESS_PROFILES_BY_ID",
  "REMOVE_ALL_BUSINESS_PROFILES": "REMOVE_ALL_BUSINESS_PROFILES"
}

export const SectorRoutes = {
  "GET_ALL_SECTORS": "GET_ALL_SECTORS",
  "GET_ONE_SECTOR": "GET_ONE_SECTOR",
  "GET_MANY_SECTORS_BY_ID": "GET_MANY_SECTORS_BY_ID",
  "POST_SECTOR": "POST_SECTOR",
  "EDIT_SECTOR": "EDIT_SECTOR",
  "REMOVE_SECTOR_BY_ID": "REMOVE_SECTOR_BY_ID",
  "REMOVE_MANY_SECTORS_BY_ID": "REMOVE_MANY_SECTORS_BY_ID",
  "REMOVE_ALL_SECTORS": "REMOVE_ALL_SECTORS"
}

export const SubSectorRoutes = {
  "GET_ALL_SUB_SECTORS": "GET_ALL_SUB_SECTORS",
  "GET_ONE_SUB_SECTOR": "GET_ONE_SUB_SECTOR",
  "GET_MANY_SUB_SECTORS_BY_ID": "GET_MANY_SUB_SECTORS_BY_ID",
  "POST_SUB_SECTOR": "POST_SUB_SECTOR",
  "EDIT_SUB_SECTOR": "EDIT_SUB_SECTOR",
  "REMOVE_SUB_SECTOR_BY_ID": "REMOVE_SUB_SECTOR_BY_ID",
  "REMOVE_MANY_SUB_SECTORS_BY_ID": "REMOVE_MANY_SUB_SECTORS_BY_ID",
  "REMOVE_ALL_SUB_SECTORS": "REMOVE_ALL_SUB_SECTORS"
}

export const ActivityRoutes = {
  "GET_ALL_ACTIVITIES": "GET_ALL_ACTIVITIES",
  "GET_ONE_ACTIVITY": "GET_ONE_ACTIVITY",
  "GET_MANY_ACTIVITIES_BY_ID": "GET_MANY_ACTIVITIES_BY_ID",
  "POST_ACTIVITY": "POST_ACTIVITY",
  "EDIT_ACTIVITY": "EDIT_ACTIVITY",
  "REMOVE_ACTIVITY_BY_ID": "REMOVE_ACTIVITY_BY_ID",
  "REMOVE_MANY_ACTIVITIES_BY_ID": "REMOVE_MANY_ACTIVITIES_BY_ID",
  "REMOVE_ALL_ACTIVITIES": "REMOVE_ALL_ACTIVITIES"
}

export const InvestmentActivityRoutes = {
  "GET_ALL_INVESTMENT_ACTIVITIES": "GET_ALL_INVESTMENT_ACTIVITIES",
  "GET_ONE_INVESTMENT_ACTIVITY": "GET_ONE_INVESTMENT_ACTIVITY",
  "GET_MANY_INVESTMENT_ACTIVITIES_BY_ID": "GET_MANY_INVESTMENT_ACTIVITIES_BY_ID",
  "POST_INVESTMENT_ACTIVITY": "POST_INVESTMENT_ACTIVITY",
  "EDIT_INVESTMENT_ACTIVITY": "EDIT_INVESTMENT_ACTIVITY",
  "REMOVE_INVESTMENT_ACTIVITY_BY_ID": "REMOVE_INVESTMENT_ACTIVITY_BY_ID",
  "REMOVE_MANY_INVESTMENT_ACTIVITIES_BY_ID": "REMOVE_MANY_INVESTMENT_ACTIVITIES_BY_ID",
  "REMOVE_ALL_INVESTMENT_ACTIVITIES": "REMOVE_ALL_INVESTMENT_ACTIVITIES"
}

export const ProjectRoutes = {
  "GET_ALL_PROJECTS": "GET_ALL_PROJECTS",
  "GET_ONE_PROJECT": "GET_ONE_PROJECT",
  "GET_MANY_PROJECTS_BY_ID": "GET_MANY_PROJECTS_BY_ID",
  "POST_PROJECT": "POST_PROJECT",
  "EDIT_PROJECT": "EDIT_PROJECT",
  "REMOVE_PROJECT_BY_ID": "REMOVE_PROJECT_BY_ID",
  "REMOVE_MANY_PROJECTS_BY_ID": "REMOVE_MANY_PROJECTS_BY_ID",
  "REMOVE_ALL_PROJECTS": "REMOVE_ALL_PROJECTS"
}

export const ManagerRoutes = {
  "GET_ALL_MANAGERS": "GET_ALL_MANAGERS",
  "GET_ONE_MANAGER": "GET_ONE_MANAGER",
  "GET_MANY_MANAGERS_BY_ID": "GET_MANY_MANAGERS_BY_ID",
  "POST_MANAGER": "POST_MANAGER",
  "EDIT_MANAGER": "EDIT_MANAGER",
  "REMOVE_MANAGER_BY_ID": "REMOVE_MANAGER_BY_ID",
  "REMOVE_MANY_MANAGERS_BY_ID": "REMOVE_MANY_MANAGERS_BY_ID",
  "REMOVE_ALL_MANAGERS": "REMOVE_ALL_MANAGERS"
}

export const ProductRoutes = {
  "GET_ALL_PRODUCTS": "GET_ALL_PRODUCTS",
  "GET_ONE_PRODUCT": "GET_ONE_PRODUCT",
  "GET_MANY_PRODUCTS_BY_ID": "GET_MANY_PRODUCTS_BY_ID",
  "POST_PRODUCT": "POST_PRODUCT",
  "EDIT_PRODUCT": "EDIT_PRODUCT",
  "REMOVE_PRODUCT_BY_ID": "REMOVE_PRODUCT_BY_ID",
  "REMOVE_MANY_PRODUCTS_BY_ID": "REMOVE_MANY_PRODUCTS_BY_ID",
  "REMOVE_ALL_PRODUCTS": "REMOVE_ALL_PRODUCTS"
}

export const WorkPermitRoutes = {
  "GET_ALL_WORK_PERMITS": "GET_ALL_WORK_PERMITS",
  "GET_ONE_WORK_PERMIT": "GET_ONE_WORK_PERMIT",
  "GET_MANY_WORK_PERMITS_BY_ID": "GET_MANY_WORK_PERMITS_BY_ID",
  "POST_WORK_PERMIT": "POST_WORK_PERMIT",
  "EDIT_WORK_PERMIT": "EDIT_WORK_PERMIT",
  "REMOVE_WORK_PERMIT_BY_ID": "REMOVE_WORK_PERMIT_BY_ID",
  "REMOVE_MANY_WORK_PERMITS_BY_ID": "REMOVE_MANY_WORK_PERMITS_BY_ID",
  "REMOVE_ALL_WORK_PERMITS": "REMOVE_ALL_WORK_PERMITS"
}

export const MessageRoutes = {
  "GET_ALL_MESSAGES": "GET_ALL_MESSAGES",
  "GET_ONE_MESSAGE": "GET_ONE_MESSAGE",
  "GET_MANY_MESSAGES_BY_ID": "GET_MANY_MESSAGES_BY_ID",
  "POST_MESSAGE": "POST_MESSAGE",
  "EDIT_MESSAGE": "EDIT_MESSAGE",
  "REMOVE_MESSAGE_BY_ID": "REMOVE_MESSAGE_BY_ID",
  "REMOVE_MANY_MESSAGES_BY_ID": "REMOVE_MANY_MESSAGES_BY_ID",
  "REMOVE_ALL_MESSAGES": "REMOVE_ALL_MESSAGES"
}

export const InvestmentPermitRoutes = {
  "GET_ALL_INVESTMENT_PERMITS": "GET_ALL_INVESTMENT_PERMITS",
  "GET_ONE_INVESTMENT_PERMIT": "GET_ONE_INVESTMENT_PERMIT",
  "GET_MANY_INVESTMENT_PERMITS_BY_ID": "GET_MANY_INVESTMENT_PERMITS_BY_ID",
  "POST_INVESTMENT_PERMIT": "POST_INVESTMENT_PERMIT",
  "EDIT_INVESTMENT_PERMIT": "EDIT_INVESTMENT_PERMIT",
  "REMOVE_INVESTMENT_PERMIT_BY_ID": "REMOVE_INVESTMENT_PERMIT_BY_ID",
  "REMOVE_MANY_INVESTMENT_PERMITS_BY_ID": "REMOVE_MANY_INVESTMENT_PERMITS_BY_ID",
  "REMOVE_ALL_INVESTMENT_PERMITS": "REMOVE_ALL_INVESTMENT_PERMITS"
}

export const InvestmentPermitRenewalRoutes = {
  "GET_ALL_INVESTMENT_PERMIT_RENEWALS": "GET_ALL_INVESTMENT_PERMIT_RENEWALS",
  "GET_ONE_INVESTMENT_PERMIT_RENEWAL": "GET_ONE_INVESTMENT_PERMIT_RENEWAL",
  "GET_MANY_INVESTMENT_PERMIT_RENEWALS_BY_ID": "GET_MANY_INVESTMENT_PERMIT_RENEWALS_BY_ID",
  "POST_INVESTMENT_PERMIT_RENEWAL": "POST_INVESTMENT_PERMIT_RENEWAL",
  "EDIT_INVESTMENT_PERMIT_RENEWAL": "EDIT_INVESTMENT_PERMIT_RENEWAL",
  "REMOVE_INVESTMENT_PERMIT_RENEWAL_BY_ID": "REMOVE_INVESTMENT_PERMIT_RENEWAL_BY_ID",
  "REMOVE_MANY_INVESTMENT_PERMIT_RENEWALS_BY_ID": "REMOVE_MANY_INVESTMENT_PERMIT_RENEWALS_BY_ID",
  "REMOVE_ALL_INVESTMENT_PERMIT_RENEWALS": "REMOVE_ALL_INVESTMENT_PERMIT_RENEWALS"
}

export const InvestmentPermitExpansionRoutes = {
  "GET_ALL_INVESTMENT_PERMIT_EXPANSIONS": "GET_ALL_INVESTMENT_PERMIT_EXPANSIONS",
  "GET_ONE_INVESTMENT_PERMIT_EXPANSION": "GET_ONE_INVESTMENT_PERMIT_EXPANSION",
  "GET_MANY_INVESTMENT_PERMIT_EXPANSIONS_BY_ID": "GET_MANY_INVESTMENT_PERMIT_EXPANSIONS_BY_ID",
  "POST_INVESTMENT_PERMIT_EXPANSION": "POST_INVESTMENT_PERMIT_EXPANSION",
  "EDIT_INVESTMENT_PERMIT_EXPANSION": "EDIT_INVESTMENT_PERMIT_EXPANSION",
  "REMOVE_INVESTMENT_PERMIT_EXPANSION_BY_ID": "REMOVE_INVESTMENT_PERMIT_EXPANSION_BY_ID",
  "REMOVE_MANY_INVESTMENT_PERMIT_EXPANSIONS_BY_ID": "REMOVE_MANY_INVESTMENT_PERMIT_EXPANSIONS_BY_ID",
  "REMOVE_ALL_INVESTMENT_PERMIT_EXPANSIONS": "REMOVE_ALL_INVESTMENT_PERMIT_EXPANSIONS"
}

export const InvestmentPermitCancellationRoutes = {
  "GET_ALL_INVESTMENT_PERMIT_CANCELLATIONS": "GET_ALL_INVESTMENT_PERMIT_CANCELLATIONS",
  "GET_ONE_INVESTMENT_PERMIT_CANCELLATION": "GET_ONE_INVESTMENT_PERMIT_CANCELLATION",
  "GET_MANY_INVESTMENT_PERMIT_CANCELLATIONS_BY_ID": "GET_MANY_INVESTMENT_PERMIT_CANCELLATIONS_BY_ID",
  "POST_INVESTMENT_PERMIT_CANCELLATION": "POST_INVESTMENT_PERMIT_CANCELLATION",
  "EDIT_INVESTMENT_PERMIT_CANCELLATION": "EDIT_INVESTMENT_PERMIT_CANCELLATION",
  "REMOVE_INVESTMENT_PERMIT_CANCELLATION_BY_ID": "REMOVE_INVESTMENT_PERMIT_CANCELLATION_BY_ID",
  "REMOVE_MANY_INVESTMENT_PERMIT_CANCELLATIONS_BY_ID": "REMOVE_MANY_INVESTMENT_PERMIT_CANCELLATIONS_BY_ID",
  "REMOVE_ALL_INVESTMENT_PERMIT_CANCELLATIONS": "REMOVE_ALL_INVESTMENT_PERMIT_CANCELLATIONS"
}

export const NotificationRoutes = {
  "GET_ALL_NOTIFICATIONS": "GET_ALL_NOTIFICATIONS",
  "GET_ONE_NOTIFICATION": "GET_ONE_NOTIFICATION",
  "GET_MANY_NOTIFICATIONS_BY_ID": "GET_MANY_NOTIFICATIONS_BY_ID",
  "POST_NOTIFICATION": "POST_NOTIFICATION",
  "EDIT_NOTIFICATION": "EDIT_NOTIFICATION",
  "REMOVE_NOTIFICATION_BY_ID": "REMOVE_NOTIFICATION_BY_ID",
  "REMOVE_MANY_NOTIFICATIONS_BY_ID": "REMOVE_MANY_NOTIFICATIONS_BY_ID",
  "REMOVE_ALL_NOTIFICATIONS": "REMOVE_ALL_NOTIFICATIONS"
}

export const InvestmentPermitAmmendmentRoutes = {
  "GET_ALL_INVESTMENT_PERMIT_AMMENDMENTS": "GET_ALL_INVESTMENT_PERMIT_AMMENDMENTS",
  "GET_ONE_INVESTMENT_PERMIT_AMMENDMENT": "GET_ONE_INVESTMENT_PERMIT_AMMENDMENT",
  "GET_MANY_INVESTMENT_PERMIT_AMMENDMENTS_BY_ID": "GET_MANY_INVESTMENT_PERMIT_AMMENDMENTS_BY_ID",
  "POST_INVESTMENT_PERMIT_AMMENDMENT": "POST_INVESTMENT_PERMIT_AMMENDMENT",
  "EDIT_INVESTMENT_PERMIT_AMMENDMENT": "EDIT_INVESTMENT_PERMIT_AMMENDMENT",
  "REMOVE_INVESTMENT_PERMIT_AMMENDMENT_BY_ID": "REMOVE_INVESTMENT_PERMIT_AMMENDMENT_BY_ID",
  "REMOVE_MANY_INVESTMENT_PERMIT_AMMENDMENTS_BY_ID": "REMOVE_MANY_INVESTMENT_PERMIT_AMMENDMENTS_BY_ID",
  "REMOVE_ALL_INVESTMENT_PERMIT_AMMENDMENTS": "REMOVE_ALL_INVESTMENT_PERMIT_AMMENDMENTS"
}