export const WORK_PERMIT_QUEUES = {
  QUEUE_FOR_WORK_PERMIT: "QUEUE_FOR_WORK_PERMIT"
}

export const RENEW_WORK_PERMIT_QUEUES = {
  QUEUE_FOR_RENEW_WORK_PERMIT: "QUEUE_FOR_RENEW_WORK_PERMIT"
}

export const REPLACE_WORK_PERMIT_QUEUES = {
  QUEUE_FOR_REPLACE_WORK_PERMIT: "QUEUE_FOR_REPLACE_WORK_PERMIT"
}

export const CANCEL_WORK_PERMIT_QUEUES = {
  QUEUE_FOR_CANCEL_WORK_PERMIT: "QUEUE_FOR_CANCEL_WORK_PERMIT"
}

export const DOCUMENT_NUMBER_QUEUES = {
  QUEUE_FOR_DOCUMENT_NUMBER: "QUEUE_FOR_DOCUMENT_NUMBER"
}