export const WorkPermitRoutes = {
  "GET_ALL_WORK_PERMITS": "GET_ALL_WORK_PERMITS",
  "GET_ONE_WORK_PERMIT": "GET_ONE_WORK_PERMIT",
  "GET_MANY_WORK_PERMITS_BY_ID": "GET_MANY_WORK_PERMITS_BY_ID",
  "POST_WORK_PERMIT": "POST_WORK_PERMIT",
  "EDIT_WORK_PERMIT": "EDIT_WORK_PERMIT",
  "REMOVE_WORK_PERMIT_BY_ID": "REMOVE_WORK_PERMIT_BY_ID",
  "REMOVE_MANY_WORK_PERMITS_BY_ID": "REMOVE_MANY_WORK_PERMITS_BY_ID",
  "REMOVE_ALL_WORK_PERMITS": "REMOVE_ALL_WORK_PERMITS"
}

export const RenewWorkPermitRoutes = {
  "GET_ALL_RENEW_WORK_PERMITS": "GET_ALL_RENEW_WORK_PERMITS",
  "GET_ONE_RENEW_WORK_PERMIT": "GET_ONE_RENEW_WORK_PERMIT",
  "GET_MANY_RENEW_WORK_PERMITS_BY_ID": "GET_MANY_RENEW_WORK_PERMITS_BY_ID",
  "POST_RENEW_WORK_PERMIT": "POST_RENEW_WORK_PERMIT",
  "EDIT_RENEW_WORK_PERMIT": "EDIT_RENEW_WORK_PERMIT",
  "REMOVE_RENEW_WORK_PERMIT_BY_ID": "REMOVE_RENEW_WORK_PERMIT_BY_ID",
  "REMOVE_MANY_RENEW_WORK_PERMITS_BY_ID": "REMOVE_MANY_RENEW_WORK_PERMITS_BY_ID",
  "REMOVE_ALL_RENEW_WORK_PERMITS": "REMOVE_ALL_RENEW_WORK_PERMITS"
}

export const ReplaceWorkPermitRoutes = {
  "GET_ALL_REPLACE_WORK_PERMITS": "GET_ALL_REPLACE_WORK_PERMITS",
  "GET_ONE_REPLACE_WORK_PERMIT": "GET_ONE_REPLACE_WORK_PERMIT",
  "GET_MANY_REPLACE_WORK_PERMITS_BY_ID": "GET_MANY_REPLACE_WORK_PERMITS_BY_ID",
  "POST_REPLACE_WORK_PERMIT": "POST_REPLACE_WORK_PERMIT",
  "EDIT_REPLACE_WORK_PERMIT": "EDIT_REPLACE_WORK_PERMIT",
  "REMOVE_REPLACE_WORK_PERMIT_BY_ID": "REMOVE_REPLACE_WORK_PERMIT_BY_ID",
  "REMOVE_MANY_REPLACE_WORK_PERMITS_BY_ID": "REMOVE_MANY_REPLACE_WORK_PERMITS_BY_ID",
  "REMOVE_ALL_REPLACE_WORK_PERMITS": "REMOVE_ALL_REPLACE_WORK_PERMITS"
}

export const CancelWorkPermitRoutes = {
  "GET_ALL_CANCEL_WORK_PERMITS": "GET_ALL_CANCEL_WORK_PERMITS",
  "GET_ONE_CANCEL_WORK_PERMIT": "GET_ONE_CANCEL_WORK_PERMIT",
  "GET_MANY_CANCEL_WORK_PERMITS_BY_ID": "GET_MANY_CANCEL_WORK_PERMITS_BY_ID",
  "POST_CANCEL_WORK_PERMIT": "POST_CANCEL_WORK_PERMIT",
  "EDIT_CANCEL_WORK_PERMIT": "EDIT_CANCEL_WORK_PERMIT",
  "REMOVE_CANCEL_WORK_PERMIT_BY_ID": "REMOVE_CANCEL_WORK_PERMIT_BY_ID",
  "REMOVE_MANY_CANCEL_WORK_PERMITS_BY_ID": "REMOVE_MANY_CANCEL_WORK_PERMITS_BY_ID",
  "REMOVE_ALL_CANCEL_WORK_PERMITS": "REMOVE_ALL_CANCEL_WORK_PERMITS"
}

export const DocumentNumberRoutes = {
  "GET_ALL_DOCUMENT_NUMBERS": "GET_ALL_DOCUMENT_NUMBERS",
  "GET_ONE_DOCUMENT_NUMBER": "GET_ONE_DOCUMENT_NUMBER",
  "GET_MANY_DOCUMENT_NUMBERS_BY_ID": "GET_MANY_DOCUMENT_NUMBERS_BY_ID",
  "POST_DOCUMENT_NUMBER": "POST_DOCUMENT_NUMBER",
  "EDIT_DOCUMENT_NUMBER": "EDIT_DOCUMENT_NUMBER",
  "REMOVE_DOCUMENT_NUMBER_BY_ID": "REMOVE_DOCUMENT_NUMBER_BY_ID",
  "REMOVE_MANY_DOCUMENT_NUMBERS_BY_ID": "REMOVE_MANY_DOCUMENT_NUMBERS_BY_ID",
  "REMOVE_ALL_DOCUMENT_NUMBERS": "REMOVE_ALL_DOCUMENT_NUMBERS"
}