export const USER_QUEUES = {
  QUEUE_FOR_USER: "QUEUE_FOR_USER",
}

export const ACCOUNT_QUEUES = {
  QUEUE_FOR_ACCOUNT: "QUEUE_FOR_ACCOUNT", 
}

export const BUSINESS_PROFILE_QUEUES = {
  QUEUE_FOR_BUSINESS_PROFILE: "QUEUE_FOR_BUSINESS_PROFILE"
}

export const CATEGORY_QUEUES = {
  QUEUE_FOR_CATEGORY: "QUEUE_FOR_CATEGORY"
}

export const PROJECT_QUEUES = {
  QUEUE_FOR_PROJECT: "QUEUE_FOR_PROJECT"
}

export const MANAGER_QUEUES = {
  QUEUE_FOR_MANAGER: "QUEUE_FOR_MANAGER"
}

export const PRODUCT_QUEUES = {
  QUEUE_FOR_PRODUCT: "QUEUE_FOR_PRODUCT"
}

export const WORK_PERMIT_QUEUES = {
  QUEUE_FOR_WORK_PERMIT: "QUEUE_FOR_WORK_PERMIT"
}

export const MESSAGE_QUEUES = {
  QUEUE_FOR_MESSAGE: "QUEUE_FOR_MESSAGE"
}

export const INVESTMENT_PERMIT_QUEUES = {
  QUEUE_FOR_INVESTMENT_PERMIT: "QUEUE_FOR_INVESTMENT_PERMIT"
}

export const INVESTMENT_PERMIT_RENEWAL_QUEUES = {
  QUEUE_FOR_INVESTMENT_PERMIT_RENEWAL: "QUEUE_FOR_INVESTMENT_PERMIT_RENEWAL"
}

export const INVESTMENT_PERMIT_EXPANSION_QUEUES = {
  QUEUE_FOR_INVESTMENT_PERMIT_EXPANSION: "QUEUE_FOR_INVESTMENT_PERMIT_EXPANSION"
}

export const INVESTMENT_PERMIT_CANCELLATION_QUEUES = {
  QUEUE_FOR_INVESTMENT_PERMIT_CANCELLATION: "QUEUE_FOR_INVESTMENT_PERMIT_CANCELLATION"
}

export const NOTIFICATION_QUEUES = {
  QUEUE_FOR_NOTIFICATION: "QUEUE_FOR_NOTIFICATION"
}

export const INVESTMENT_PERMIT_AMMENDMENT_QUEUES = {
  QUEUE_FOR_INVESTMENT_PERMIT_AMMENDMENT: "QUEUE_FOR_INVESTMENT_PERMIT_AMMENDMENT"
}